name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  continuous-integration:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - uses: actions/checkout@v1
      - name: Install Python Setuptools
        run: sudo apt-get install -y python3-setuptools
        if: runner.os == 'Linux'
      - name: Install Jupyter Notebook
        run: python3 -m pip install notebook
      - name: Test
        run: swift test
